---
permalink: manage/task_change_the_administrative_password.html 
sidebar: sidebar 
keywords:  
summary: Você pode alterar a senha de administrador das ferramentas do ONTAP após a implantação usando o console de manutenção. 
---
= Altere a senha do administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a senha de administrador das ferramentas do ONTAP após a implantação usando o console de manutenção. A senha expira após 90 dias.

*Passos*

. No vCenter Server, abra um console para as ferramentas do ONTAP.
. Inicie sessão como utilizador de manutenção.
. Entre `1` no console de manutenção para selecionar Application Configuration (Configuração da aplicação).
. Digite `6` para selecionar *alterar a senha de usuário 'administrador'*.
. Introduza uma palavra-passe com um mínimo de oito carateres e um máximo de 30 carateres. A senha deve conter um mínimo de um caractere superior, um inferior, um dígito e um especial. O aviso de expiração da palavra-passe é apresentado após 75 dias de reposição da palavra-passe. A nova palavra-passe não pode ser igual à última palavra-passe utilizada.
+
Se você não seguir as recomendações de senha, a opção do console de manutenção está limitada a alterar a senha. Quando a senha tiver expirado, você será solicitado a alterar a senha.

. Introduza `y` na caixa de diálogo de confirmação.

